import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/ui/Navbar";
import Providers from "./providers";

export const metadata: Metadata = {
  title: "RAMSoc UNSW",
  description: "Generated by create next app",
  icons: { icon: "/favicon.svg", apple: "/favicon.svg" },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-stone-50 antialiased`}>
        <Providers>
          <Navbar></Navbar>
          {children}
          <footer className="flex h-12 w-full items-center justify-center bg-primary-950 text-primary-50">
            Copyright © 2025 UNSW RAMSoc Society - All Rights Reserved.
          </footer>
        </Providers>
      </body>
    </html>
  );
}
