name: Next.js App CI
on:
  push:
    branches: ["*"]
    paths-ignore:
      - "README.md"
      - "docs/**"
  pull_request:
    branches: [main, dev]
    paths-ignore:
      - "README.md"
      - "docs/**"
jobs:
  all-cli-checks:
    runs-on: ubuntu-latest
    env:
      META_API_PAGE_ACCESS_TOKEN: ${{ secrets.META_API_PAGE_ACCESS_TOKEN }}
      CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
      CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Enable corepack
        run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: "yarn"
      - name: Install dependencies
        run: yarn
      - name: Run linter
        run: yarn lint
      - name: Build application
        run: yarn pages:build
