name: Next.js App CI
on:
  push:
    branches: ["*"]
    paths-ignore:
      - "README.md"
      - "docs/**"
  pull_request:
    branches: [master, dev]
    paths-ignore:
      - "README.md"
      - "docs/**"
jobs:
  all-cli-checks:
    runs-on: ubuntu-latest
    env:
      REACT_APP_CONTENTFUL_ACCESS_TOKEN: ${{ secrets.META_API_PAGE_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: yarn
      - name: Run linter
        run: yarn lint
      - name: Build application
        run: yarn build
